name       : pyexiv2
version    : 0.3.2
release    : 4
source     :
    - http://launchpad.net/pyexiv2/0.3.x/0.3.2/+download/pyexiv2-0.3.2.tar.bz2 : 0abc117c6afa71f54266cb91979a5227f60361db1fcfdb68ae9615398d7a2127
license    : GPL-2.0
component  : desktop.library
summary    : Python bindings to exiv2
description: |
    pyexiv2, a python binding to exiv2 (http://exiv2.org/), the C++ library for manipulation of EXIF, IPTC and XMP image metadata. It is a python module that allows your python scripts to read and write metadata (EXIF, IPTC, XMP, thumbnails) embedded in image files (JPEG, TIFF, etc).
builddeps  :
    - pkgconfig(exiv2)
    - libboost-devel
    - scons
build      : |
    scons
install    : |
    scons DESTDIR=%installroot% install
